### PR TITLE
change distri to os_family for el

### PR DESCRIPTION
**Pull request by rndmh3ro**

### CODE REVIEW

**Comment by darkwizard242** [comment]
Thanks @rndmh3ro for the patch. Looks good, built successfully along with the molecule test.

Before I merge it - just out of my personal curiosity, what led to changing the way facts were being utilized?

**Comment by rndmh3ro** [comment]
@darkwizard242, sorry I wanted to write something to the PR but forgot!

The reason is that `os_family` of RedHat includes rhel, centos, fedora and amazon, so the role will work on more operating systems.

`ansible_facts.distribution` instead of `ansible_distribution` because the namespacing was introduced by Ansible.

**Comment by darkwizard242** [comment]
@rndmh3ro - Totally makes sense .. Thank you very much identifying that and for the PR.

Will approve and merge it to master, once the CI builds runs successfully for master branch - I will roll out a release so that Ansible Galaxy has the latest version of the role with your changes; and will notify you.

**Comment by darkwizard242** [comment]
@rndmh3ro  [1.0.9](https://github.com/darkwizard242/ansible-role-inspec/releases/tag/1.0.9) built and released to Ansible galaxy role [darkwizard242.inspec](https://galaxy.ansible.com/darkwizard242/inspec) . Thanks again!

**Comment by rndmh3ro** [comment]
Thank you!

**Pull request merged**
