### PR TITLE
Toggle for disabling EL GPG check for installer.

### PR DESCRIPTION
**Pull request by tohch4**
Fixes issue darkwizard242/ansible-role-inspec#6.

### CODE REVIEW

**Comment by tohch4** [comment]
@darkwizard242, I marked this as draft for now. Should I include with CentOS molecule test to test it works or you OK with it as is? I see there is only a Ubuntu test for now.

If you are OK for now, I will remove the draft status and you can review for a final merge if you'd like. Thanks for your patience.

**Comment by tohch4** [comment]
Wait, apologies, I am confusing this with a different issue with an Inspector Agent role, I need to actually implement this differently and include the signing by default. Apologies for the confusion.

Please hold.

**Comment by darkwizard242** [comment]
@tohch4 - Yah I was going to ask about it since when I looked up yum module for [disable_gpg_check](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_module.html#parameter-disable_gpg_check) parameter, it is set to `no` by default if not explicitly set to `yes` and applies only if state is passed as `latest` or `present`.

No worries though, I have a very minor update to make i.e. changing the value for `inspec_version` to match the latest stable version but for now, I will leave it be until your changes changes are merged in. Once you push new changes to this PR for addressing the GPG keys issue.. I will merge the PR and update the version variable, then push out a new GitHub/AnsibleGalaxy release 👍🏻

**Comment by tohch4** [comment]
Yeah, thanks for the comments and the notes, so I conditionally skip adding the key and checks. So by default, it now does the key check unless `inspec_el_disable_gpg_check` is set to `yes` or `true`. I presume there is no harm checking it by default?

I also did add at least the CentOS 7 from your Docker Hub to run the tests as and it will install the key and run the install with that. I added the key from upstream. This worked once I set up and used the local repo folder name in `converge.yml` from `- role: darkwizard242.inspec` to `- role: ansible-role-inspec` and it passed. Output below. Is that sufficient?

Also, I will definitely check out your CIS role, thanks!

```sh
$ MOLECULE_DISTRO=centos molecule test
--> Test matrix
    
└── default
    ├── lint
    ├── destroy
    ├── syntax
    ├── create
    ├── converge
    ├── verify
    ├── cleanup
    └── destroy
    
--> Scenario: 'default'
--> Action: 'lint'
--> Executing: yamllint .
ansible-lint
flake8
--> Scenario: 'default'
--> Action: 'destroy'
--> Sanity checks: 'docker'
    
    PLAY [Destroy] *****************************************************************
    
    TASK [Destroy molecule instance(s)] ********************************************
    changed: [localhost] => (item=ubuntu-18.04)
    changed: [localhost] => (item=centos-7)
    
    TASK [Wait for instance(s) deletion to complete] *******************************
    ok: [localhost] => (item={'started': 1, 'finished': 0, 'ansible_job_id': '752935580989.7386', 'results_file': '/Users/astein/.ansible_async/752935580989.7386', 'changed': True, 'failed': False, 'item': {'image': 'darkwizard242/ansible:ubuntu-18.04', 'name': 'ubuntu-18.04', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']}, 'ansible_loop_var': 'item'})
    ok: [localhost] => (item={'started': 1, 'finished': 0, 'ansible_job_id': '933499546987.7407', 'results_file': '/Users/astein/.ansible_async/933499546987.7407', 'changed': True, 'failed': False, 'item': {'image': 'darkwizard242/ansible:centos-7', 'name': 'centos-7', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']}, 'ansible_loop_var': 'item'})
    
    TASK [Delete docker network(s)] ************************************************
    
    PLAY RECAP *********************************************************************
    localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
    
--> Scenario: 'default'
--> Action: 'syntax'
    
    playbook: /Users/astein/Code/ansible-role-inspec/molecule/default/converge.yml
--> Scenario: 'default'
--> Action: 'create'
    
    PLAY [Create] ******************************************************************
    
    TASK [Log into a Docker registry] **********************************************
    skipping: [localhost] => (item={'image': 'darkwizard242/ansible:ubuntu-18.04', 'name': 'ubuntu-18.04', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']}) 
    skipping: [localhost] => (item={'image': 'darkwizard242/ansible:centos-7', 'name': 'centos-7', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']}) 
    
    TASK [Check presence of custom Dockerfiles] ************************************
    ok: [localhost] => (item={'image': 'darkwizard242/ansible:ubuntu-18.04', 'name': 'ubuntu-18.04', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']})
    ok: [localhost] => (item={'image': 'darkwizard242/ansible:centos-7', 'name': 'centos-7', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']})
    
    TASK [Create Dockerfiles from image names] *************************************
    skipping: [localhost] => (item={'image': 'darkwizard242/ansible:ubuntu-18.04', 'name': 'ubuntu-18.04', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']}) 
    skipping: [localhost] => (item={'image': 'darkwizard242/ansible:centos-7', 'name': 'centos-7', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']}) 
    
    TASK [Discover local Docker images] ********************************************
    ok: [localhost] => (item={'changed': False, 'skipped': True, 'skip_reason': 'Conditional result was False', 'item': {'image': 'darkwizard242/ansible:ubuntu-18.04', 'name': 'ubuntu-18.04', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']}, 'ansible_loop_var': 'item', 'i': 0, 'ansible_index_var': 'i'})
    ok: [localhost] => (item={'changed': False, 'skipped': True, 'skip_reason': 'Conditional result was False', 'item': {'image': 'darkwizard242/ansible:centos-7', 'name': 'centos-7', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']}, 'ansible_loop_var': 'item', 'i': 1, 'ansible_index_var': 'i'})
    
    TASK [Build an Ansible compatible image (new)] *********************************
    skipping: [localhost] => (item=molecule_local/darkwizard242/ansible:ubuntu-18.04) 
    skipping: [localhost] => (item=molecule_local/darkwizard242/ansible:centos-7) 
    
    TASK [Create docker network(s)] ************************************************
    
    TASK [Determine the CMD directives] ********************************************
    ok: [localhost] => (item={'image': 'darkwizard242/ansible:ubuntu-18.04', 'name': 'ubuntu-18.04', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']})
    ok: [localhost] => (item={'image': 'darkwizard242/ansible:centos-7', 'name': 'centos-7', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']})
    
    TASK [Create molecule instance(s)] *********************************************
    changed: [localhost] => (item=ubuntu-18.04)
    changed: [localhost] => (item=centos-7)
    
    TASK [Wait for instance(s) creation to complete] *******************************
    FAILED - RETRYING: Wait for instance(s) creation to complete (300 retries left).
    changed: [localhost] => (item={'started': 1, 'finished': 0, 'ansible_job_id': '158010777241.7562', 'results_file': '/Users/astein/.ansible_async/158010777241.7562', 'changed': True, 'failed': False, 'item': {'image': 'darkwizard242/ansible:ubuntu-18.04', 'name': 'ubuntu-18.04', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']}, 'ansible_loop_var': 'item'})
    changed: [localhost] => (item={'started': 1, 'finished': 0, 'ansible_job_id': '91711041731.7583', 'results_file': '/Users/astein/.ansible_async/91711041731.7583', 'changed': True, 'failed': False, 'item': {'image': 'darkwizard242/ansible:centos-7', 'name': 'centos-7', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']}, 'ansible_loop_var': 'item'})
    
    PLAY RECAP *********************************************************************
    localhost                  : ok=5    changed=2    unreachable=0    failed=0    skipped=4    rescued=0    ignored=0
    
--> Scenario: 'default'
--> Action: 'converge'
    
    PLAY [Converge] ****************************************************************
    
    TASK [Gathering Facts] *********************************************************
            ok: [ubuntu-18.04]
    ok: [centos-7]
    
    TASK [ansible-role-inspec : Debian OS | Downloading and installing inspec 4.22.22] ***
    skipping: [centos-7]
    skipping: [ubuntu-18.04]
    
    TASK [ansible-role-inspec : Ubuntu OS | Downloading and installing inspec 4.22.22] ***
    skipping: [centos-7]
    changed: [ubuntu-18.04]
    
    TASK [ansible-role-inspec : EL Family | Download Chef signing key for RPM packages] ***
    skipping: [ubuntu-18.04]
    changed: [centos-7]
    
    TASK [ansible-role-inspec : EL Family | Downloading and extracting inspec 4.22.22] ***
    skipping: [ubuntu-18.04]
    changed: [centos-7]
    
    PLAY RECAP *********************************************************************
    centos-7                   : ok=3    changed=2    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0
    ubuntu-18.04               : ok=2    changed=1    unreachable=0    failed=0    skipped=3    rescued=0    ignored=0
    
--> Scenario: 'default'
--> Action: 'verify'
--> Executing Testinfra tests found in /Users/astein/Code/ansible-role-inspec/molecule/default/tests/...
    ============================= test session starts ==============================
    platform darwin -- Python 3.8.5, pytest-6.1.0, py-1.9.0, pluggy-0.13.1 -- /Users/astein/.pyenv/versions/ansible/bin/python
    rootdir: /Users/astein/Code/ansible-role-inspec/molecule/default
    plugins: testinfra-5.3.1
collected 6 items                                                              
    
    tests/test_default.py::test_inspec_binary_exists[ansible://centos-7] PASSED [ 16%]
    tests/test_default.py::test_inspec_binary_file[ansible://centos-7] PASSED [ 33%]
    tests/test_default.py::test_inspec_binary_which[ansible://centos-7] PASSED [ 50%]
    tests/test_default.py::test_inspec_binary_exists[ansible://ubuntu-18.04] PASSED [ 66%]
    tests/test_default.py::test_inspec_binary_file[ansible://ubuntu-18.04] PASSED [ 83%]
    tests/test_default.py::test_inspec_binary_which[ansible://ubuntu-18.04] PASSED [100%]
    
    ============================== 6 passed in 3.58s ===============================
Verifier completed successfully.
--> Scenario: 'default'
--> Action: 'cleanup'
Skipping, cleanup playbook not configured.
--> Scenario: 'default'
--> Action: 'destroy'
    
    PLAY [Destroy] *****************************************************************
    
    TASK [Destroy molecule instance(s)] ********************************************
    changed: [localhost] => (item=ubuntu-18.04)
    changed: [localhost] => (item=centos-7)
    
    TASK [Wait for instance(s) deletion to complete] *******************************
    FAILED - RETRYING: Wait for instance(s) deletion to complete (300 retries left).
    changed: [localhost] => (item={'started': 1, 'finished': 0, 'ansible_job_id': '149752478363.7767', 'results_file': '/Users/astein/.ansible_async/149752478363.7767', 'changed': True, 'failed': False, 'item': {'image': 'darkwizard242/ansible:ubuntu-18.04', 'name': 'ubuntu-18.04', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']}, 'ansible_loop_var': 'item'})
    changed: [localhost] => (item={'started': 1, 'finished': 0, 'ansible_job_id': '520722657504.7788', 'results_file': '/Users/astein/.ansible_async/520722657504.7788', 'changed': True, 'failed': False, 'item': {'image': 'darkwizard242/ansible:centos-7', 'name': 'centos-7', 'pre_build_image': True, 'privileged': True, 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro']}, 'ansible_loop_var': 'item'})
    
    TASK [Delete docker network(s)] ************************************************
    
    PLAY RECAP *********************************************************************
    localhost                  : ok=2    changed=2    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
    
--> Pruning extra files from scenario ephemeral directory
```

**Comment by tohch4** [comment]
Also, I am looking at the test, why is `centos-7` is not unique enough. I am not familiar with that molecule tooling issue. Thoughts?

**Comment by tohch4** [comment]
> @tohch4 - Change to include centos7 in the molecule configuration file may not be required as the TravisCI build plays the role out using molecule on various systems that are defined in [.travis.yml file](https://github.com/darkwizard242/ansible-role-inspec/blob/master/.travis.yml#L16) to overwrite the value for DISTRO variable. For local testing, I had set it to ubuntu-18.04 .. However, should you need to test with centos-7 locally, just need to pass centos-7 in as the value for DISTRO variable when calling molecule test like the following:

Woops and now I see that, I asked about the error above. I guess I looked at the PR without being logged in and missed the obvious bit about the PR check, my bad. Should I remove the CentOS block to resolve then?

**Comment by darkwizard242** [comment]
> > @tohch4 - Change to include centos7 in the molecule configuration file may not be required as the TravisCI build plays the role out using molecule on various systems that are defined in [.travis.yml file](https://github.com/darkwizard242/ansible-role-inspec/blob/master/.travis.yml#L16) to overwrite the value for DISTRO variable. For local testing, I had set it to ubuntu-18.04 .. However, should you need to test with centos-7 locally, just need to pass centos-7 in as the value for DISTRO variable when calling molecule test like the following:
> 
> Woops and now I see that, I asked about the error above. I guess I looked at the PR without being logged in and missed the obvious bit about the PR check, my bad. Should I remove the CentOS block to resolve then?

@tohch4 - Yup, we should be good with removing the centos-7 block in molecule's config (i.e. molecule.yml). My personal preference has been ubuntu-18.04 when developing locally - so I set that as the default value for DISTRO variable unless any other OS is passed like in the TravisCI build, so generally I try to make sure to allow TravisCI to provision role via molecule to different systems for validation 😇

Also, in response to your query around "I presume there is no harm checking it by default?" --> I agree, there is no harm and I like it👍🏻

**Comment by tohch4** [comment]
OK cool, CentOS 7 looks good. Thanks for your prompt response!

**Comment by darkwizard242** [comment]
@tohch4 - It's my pleasure and I really appreciate you work 👍🏻 Are you good with these changes? I hope they resolve the issue in the STIG'd AMI builds.

If you are good with the changes and the TravisCI build passes, I can go ahead and merge it to master.

**Pull request merged**
